---
AllCops:
  NewCops: disable
  DisplayCopNames: true
  TargetRubyVersion: '2.4'
  Include:
    - "lib/**/*.rb"
    - "**/Vagrantfile"
    - "spec/**/*.rb"
    - "acceptance/**/*.rb"
    - "**/Rakefile"
    - "**/*.task"
  Exclude:
    - "bin/*"
    - "modules/**/*"
    - ".vendor/**/*"
    - ".bundle/**/*"
    - "**/Gemfile"
    - "pkg/**/*"
    - "spec/fixtures/**/*"
    - "vendor/**/*"
    - ".vagrant/**/*"
  DisabledByDefault: false
Metrics/LineLength:
  Description: People have wide screens, use them.
  Max: 200
  Enabled: true
Style/BlockDelimiters:
  Description: Prefer braces for chaining. Mostly an aesthetical choice. Better to
    be consistent then.
  EnforcedStyle: braces_for_chaining
  Enabled: true
Style/ClassAndModuleChildren:
  Description: Compact style reduces the required amount of indentation.
  EnforcedStyle: compact
  Enabled: true
Style/EmptyElse:
  Description: Enforce against empty else clauses, but allow `nil` for clarity.
  EnforcedStyle: empty
  Enabled: true
Style/FormatString:
  EnforcedStyle: percent
  Enabled: true
Style/FormatStringToken:
  EnforcedStyle: template
  Enabled: true
Style/Lambda:
  Description: Prefer the keyword for easier discoverability.
  EnforcedStyle: literal
  Enabled: true
Style/RegexpLiteral:
  EnforcedStyle: percent_r
  Enabled: true
Style/TernaryParentheses:
  Description: Checks for use of parentheses around ternary conditions. Enforce parentheses
    on complex expressions for better readability, but seriously consider breaking
    it up.
  EnforcedStyle: require_parentheses_when_complex
  Enabled: true
Style/TrailingCommaInArguments:
  Description: Prefer always trailing comma on multiline argument lists. This makes
    diffs, and re-ordering nicer.
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInHashLiteral:
  Description: Prefer always trailing comma on multiline literals. This makes diffs,
    and re-ordering nicer.
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/TrailingCommaInArrayLiteral:
  Description: Prefer always trailing comma on multiline literals. This makes diffs,
    and re-ordering nicer.
  EnforcedStyleForMultiline: comma
  Enabled: true
Style/SymbolArray:
  Description: Using percent style obscures symbolic intent of array's contents.
  EnforcedStyle: brackets
  Enabled: true
Style/Documentation:
  Exclude:
  - spec/**/*
  Enabled: false
Style/WordArray:
  EnforcedStyle: brackets
  Enabled: true
Style/CollectionMethods:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Enabled: true
Style/StringMethods:
  Enabled: true
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: true
Style/StringLiterals:
  Enabled: false
Naming/FileName:
  Enabled: false
Style/FrozenStringLiteralComment:
  Exclude:
    - "**/Vagrantfile"
Metrics/BlockLength:
  Exclude:
    - "**/Vagrantfile"
    - "spec/**/*.rb"
    - "acceptance/**/*.rb"
Style/RescueStandardError:
  EnforcedStyle: implicit
Lint/MissingSuper:
  Enabled: false
