name: Spec and Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  spec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - vagrant: 'v2.2.1'
            ruby: 2.5
          - vagrant: 'v2.2.14'
            ruby: 2.5
          - vagrant: 'HEAD'
            ruby: 2.6
          - vagrant: 'HEAD'
            ruby: 2.7
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Setup Ruby ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/gems
          key: ${{ runner.os }}-pr-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-pr-
            ${{ runner.os }}-

      - name: Install gems
        env:
          TEST_VAGRANT_VERSION: ${{ matrix.vagrant }}
        run: |
          gem install bundler
          bundle config path vendor/gems
          bundle config jobs 8
          bundle config retry 3
          bundle install
          bundle clean

      - name: bundler environment
        env:
          TEST_VAGRANT_VERSION: ${{ matrix.vagrant }}
        run: |
          bundle env

      - name: Rubocop
        env:
          TEST_VAGRANT_VERSION: ${{ matrix.vagrant }}
        run: |
          bundle exec rake rubocop

      - name: Spec Tests
        env:
          TEST_VAGRANT_VERSION: ${{ matrix.vagrant }}
        run: |
          bundle exec rake spec
